GET http://localhost:8000/api/street_market
Content-Type: application/json
Accept: application/json
###

POST http://localhost:8000/api/street_market
Content-Type: application/json
Accept: application/json

{}
###
